# Background Config (Takes a snapshot of your screen and blurs it)
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# General Layout settings
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# The Input Box (Password field)
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 3
    dots_size = 0.25 # Size of input dots
    dots_spacing = 0.4 # Spacing of input dots
    dots_center = true
    
    # Outer ring accents (Catppuccin Mocha colors)
    outer_color = rgb(cba6f7) # Mauve
    inner_color = rgb(1e1e2e) # Base dark
    font_color = rgb(cdd6f4)  # Text
    
    fade_on_empty = false
    placeholder_text = <span font_family="JetBrains Mono">Enter Password...</span>
    hide_input = false
    
    # This turns on character indicators explicitly
    fail_color = rgb(f38ba8) # Red on wrong pass
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    
    position = 0, -50
    halign = center
    valign = center
}

# The Clock Layout
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 80
    font_family = JetBrains Mono Bold
    position = 0, 120
    halign = center
    valign = center
}

# The Date Layout
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
}
